spring.application.name=Java Servers - SQL DB
server.port=8082


spring.datasource.url=jdbc:postgresql://localhost:5432/anime_db
spring.datasource.username=postgres
spring.datasource.password=2020

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
